### ISSUE TITLE
OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [PostrelPP/oop-put-course_I12#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [ ] Too few classes (only one) - we need something 
- [ ] Rename repository to **oop-put-course**
- [ ] Rename files to task1.cpp
- [ ] Format code properly - follow proper conventions e.g. [this](https://google.github.io/styleguide/cppguide.html)
- [ ] Don't use polish language
